Ccp 857
shopgate/ext-upselling pull request #1
Opened 2018-10-12 11:46 UTC by sznowicki

# Pull Request Template

## Description

First implementation with Product Detail Page swiper.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I updated the CHANGELOG.md

2018-10-16 08:44 UTC, Carsten89 reviewed
some of your test files are "index.spec.jsx" and some "spec.jsx". please be consistent

2018-10-16 08:44 UTC, Carsten89 commented on frontend/portals/ProductDetailPage/index.spec.jsx
> +      <ProductDetailPage name="mockedPosition" type="mockedType" />
there is no prop `type` (anymore)

2018-10-16 09:26 UTC, sznowicki commented on frontend/portals/ProductDetailPage/index.spec.jsx
> +      <ProductDetailPage name="mockedPosition" type="mockedType" />
Removed

2018-10-16 09:28 UTC, sznowicki commented
> some of your test files are "index.spec.jsx" and some "spec.jsx". please be consistent

Renamed.

2018-10-17 13:36 UTC, Carsten89 requested changes

2018-10-17 13:36 UTC, Carsten89 commented on frontend/components/Slider/index.jsx
> +    dispatch(getProductRelationsAction({
we should use some limit here, because there is no default limit set in pwa for this request

2018-10-17 13:36 UTC, Carsten89 commented on frontend/selectors/index.js
> +export const getProductRelationsFiletered = params => createSelector(
typo getProductRelationsFil**e**tered

2018-10-17 13:36 UTC, Carsten89 commented on frontend/selectors/index.js
> +
ESLint error
```suggestion
```

2018-10-17 13:36 UTC, Carsten89 commented on frontend/components/PageComponentFactory/index.spec.jsx
> +    expect(component.find('#view').length).toBe(1);
hint, you could do and save the .length
```suggestion
    expect(component.exists('#view')).toBe(true);
```

2018-10-17 13:36 UTC, Carsten89 commented on frontend/components/Slider/components/DefaultSlider/index.jsx
> +        const product = products[id] || undefined;
```suggestion
        const product = products[id];
```

2018-10-17 13:36 UTC, Carsten89 commented on frontend/components/Slider/components/DefaultSlider/components/Item/components/PlaceholderCard/index.spec.jsx
> +});
ESlint error 
```suggestion
});

```

2018-10-17 13:36 UTC, Carsten89 commented on frontend/components/Slider/components/DefaultSlider/index.spec.jsx
> +import React, { Component as MockedComponent } from 'react';
this file contains some ESlint erros

2018-10-17 13:36 UTC, Carsten89 commented on frontend/components/Slider/components/DefaultSlider/index.spec.jsx
> +  it('should render gmd slider', () => {
```suggestion
  it('should render iOS slider', () => {
```

2018-10-17 15:26 UTC, sznowicki commented on frontend/components/Slider/index.jsx
> +    dispatch(getProductRelationsAction({
It's PWA bug. I'll fix it there

2018-10-17 15:31 UTC, sznowicki commented on frontend/components/Slider/index.jsx
> +    dispatch(getProductRelationsAction({
https://github.com/shopgate/pwa/pull/328

2018-10-17 15:33 UTC, sznowicki commented on frontend/components/PageComponentFactory/index.spec.jsx
> +    expect(component.find('#view').length).toBe(1);
True

2018-10-17 15:35 UTC, sznowicki commented on frontend/components/Slider/components/DefaultSlider/index.jsx
> +        const product = products[id] || undefined;
Done

2018-10-17 15:35 UTC, sznowicki commented on frontend/components/Slider/components/DefaultSlider/components/Item/components/PlaceholderCard/index.spec.jsx
> +});
🤫

2018-10-17 15:36 UTC, sznowicki commented on frontend/components/Slider/components/DefaultSlider/index.spec.jsx
> +import React, { Component as MockedComponent } from 'react';
🤫

2018-10-17 15:36 UTC, sznowicki commented on frontend/components/Slider/components/DefaultSlider/index.spec.jsx
> +  it('should render gmd slider', () => {
🤫

2018-10-22 12:18 UTC, Carsten89 reviewed
![image](https://user-images.githubusercontent.com/5811286/47291726-044aed80-d605-11e8-8f47-3e681f237248.png)
sometimes the placeholders stay there forever

2018-10-22 12:19 UTC, Carsten89 reviewed
![image](https://user-images.githubusercontent.com/5811286/47291839-6ad00b80-d605-11e8-8cc5-34459a3fd1d6.png)

2018-10-22 12:31 UTC, merged