Pwa 6
shopgate/ext-upselling pull request #4
Opened 2019-02-07 13:25 UTC by sznowicki

# Pull Request Template

## Description

- PWA6 migration
- Bring back placeholders on Sliders
- GMD/IOS styling fixes

## Type of change

- [x] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md

2019-02-07 19:46 UTC, aaron-martin requested changes
I found two small issues. Sorry to be so picky.

2019-02-07 19:46 UTC, aaron-martin commented on CHANGELOG.md
>  [Unreleased]: https://github.com/shopgate/ext-upselling/compare/v1.1.0...HEAD
Unreleased link should be updated to https://github.com/shopgate/ext-upselling/compare/v2.0.0...HEAD

2019-02-07 19:46 UTC, aaron-martin commented on frontend/components/PDPSlider/index.jsx
>   * @returns {Object}
jsDoc missing props param

2019-02-08 08:37 UTC, sznowicki commented on frontend/components/PDPSlider/index.jsx
>   * @returns {Object}
done

2019-02-08 08:38 UTC, sznowicki commented on CHANGELOG.md
>  [Unreleased]: https://github.com/shopgate/ext-upselling/compare/v1.1.0...HEAD
Done.

2019-02-08 08:38 UTC, sznowicki commented
> I found two small issues. Sorry to be so picky.

No need to be sorry. That's the review process ;)

2019-02-08 08:56 UTC, Carsten89 commented on frontend/components/Slider/index.jsx
> +        // Should never happen in real life. But it after timeout, there's still not even one
```suggestion
        // Should never happen in real life. But if after timeout, there's still not even one
```

2019-02-08 09:07 UTC, merged