CCP-1700: Added new portal position on PDP
shopgate/ext-upselling pull request #6
Opened 2019-09-11 13:12 UTC by patrick-scherer

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md

2019-09-11 15:19 UTC, Carsten89 requested changes

2019-09-11 15:19 UTC, Carsten89 commented on CHANGELOG.md
> +## [2.0.2] - 2019-09-11
should be 2.1.0 because it's a new feature

2019-09-11 15:57 UTC, aaron-martin requested changes
I only checked the portal position. That looks fine though I think you should make the improvement I suggested to the configuration. I did not check how the slider is rendered. There was an issue with the recently viewed product slider sizing. Make sure the slider renders as expected.

2019-09-11 15:57 UTC, aaron-martin commented on extension-config.json
> +      "id": "PDPDescriptionBefore",
There doesn't need to be separate configurations for PDPDescriptionBefore, PDPDescriptionAfter, and PDPHeaderAfter.  You can replace theme with one configuration where the value of target is an array like this: 
```json
{
      "id": "PDPPageSlider",
      "type": "portals",
      "path": "frontend/portals/ProductDetailPageSlider",
      "target": ["product.description.before", "product.description.after", "product.header.after"]
    },
```

2019-09-12 09:14 UTC, patrick-scherer commented on CHANGELOG.md
> +## [2.0.2] - 2019-09-11
done

2019-09-12 09:14 UTC, patrick-scherer commented on extension-config.json
> +      "id": "PDPDescriptionBefore",
done

2019-09-12 11:25 UTC, aaron-martin approved these changes

2019-09-12 11:32 UTC, Carsten89 approved these changes

2019-09-13 07:33 UTC, merged